#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)

* Архив окружения

** DONE Придумать более конкретное название программы
   CLOSED: [2025-06-14 Сб 10:28]
   :PROPERTIES:
   :issue_id: 13
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-14 Сб 10:29
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-07 Сб 21:04]

** DONE Сделать подходящий для общего пользования README
   CLOSED: [2025-06-14 Сб 10:31]
   :PROPERTIES:
   :issue_id: 14
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-14 Сб 10:32
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-07 Сб 21:04]

** DONE Сделать лог версий в NEWS
   CLOSED: [2025-06-14 Сб 10:33]
   :PROPERTIES:
   :issue_id: 15
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-14 Сб 10:33
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-07 Сб 21:04]

** DONE Сделать Makefile
   CLOSED: [2025-06-14 Сб 10:34]
   :PROPERTIES:
   :issue_id: 16
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-14 Сб 10:35
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-07 Сб 21:04]

** DONE Создать репозиторий
   CLOSED: [2025-06-14 Сб 10:35]
   :PROPERTIES:
   :issue_id: 17
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-14 Сб 10:36
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-07 Сб 21:04]

** DONE Создать страницу man
   CLOSED: [2025-06-16 Пн 13:16]
   :PROPERTIES:
   :issue_id: 20
   :issue_type: task
   :ARCHIVE_TIME: 2025-06-16 Пн 13:17
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Окружение
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-06 Пт 23:56]

   Нужно создать страницу помощи, в которой написать разные конкретные
   примеры для закачки с разных сайтов, чтобы незнакомый пользователь
   мог повторить настройки и у него по ним получилось скачать файл.

   [2025-06-14 Сб 10:18]

   Добавить пример с несколькими прыжками по сайту и описать его.


* Архив задач

** DONE Задать имя файла рядом со ссылкой в списке ссылок
   CLOSED: [2025-07-02 Ср 00:37]
   :PROPERTIES:
   :issue_id: 3
   :issue_type: task
   :ARCHIVE_TIME: 2025-07-02 Ср 01:07
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-06-14 Сб 10:18]

   Возможно для этого больше подойдёт отдельный файл с именами по
   порядку. Имена можно брать и помечать как взятые уже и присвоенные
   каким-то файлам. Надо обдумать этот вопрос, чтобы не перегружать
   сильно файл со ссылками ограничивающим синтаксисом.

   [2025-07-02 Ср 00:38]

   Добавил разделитель возле ссылки, который задаётся в файле
   конфигурации. Если разделитель есть, то берётся имя файла после
   разделителя. Если разделителя нет, то устанавливается имя по
   порядку.

** CANCEL Сделать настройку для изображения браузера
   CLOSED: [2025-07-25 Пт 23:20]
   :PROPERTIES:
   :issue_id: 7
   :issue_type: task
   :ARCHIVE_TIME: 2025-07-25 Пт 23:24
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: CANCEL
   :END:

   [2025-06-07 Сб 21:04]

   - агента
   - реферера

   [2025-07-25 Пт 23:21]

   Так как команды для скачивания стали параметрами, то прямо в этих
   командах и задаётся теперь и браузер, и реферер, и печенье.

** DONE Добавить возможность детализации уведомлений
   CLOSED: [2025-11-16 Вс 20:34]
   :PROPERTIES:
   :issue_id: 22
   :issue_type: task
   :ARCHIVE_TIME: 2025-11-16 Вс 20:36
   :ARCHIVE_FILE: ~/prog/projects/python/julo/julo/tasks/tasks.org
   :ARCHIVE_OLPATH: Задачи
   :ARCHIVE_CATEGORY: tasks
   :ARCHIVE_TODO: DONE
   :END:

   [2025-11-15 Сб 07:51]

   Сейчас при закачивании файла показывается только факт завершения
   закачки и больше ничего, поэтому имя закачанного файла не
   видно. Изначально это было сделано специально, чтобы было видно
   только, что закачка идёт и продвигается, так как ссылки закачки
   скрывались, а осмысленных имён у файлов не было в то время.

   Сейчас появилась опция сохранения файла сразу под заданным именем,
   поэтому нужно добавить опцию, чтобы можно было включать имя файла в
   уведомление. Если опция включена, то в каждом уведомлении пишется
   имя закачанного файла, а если опция выключена, то уведомление
   отображается без имени файла.

   - в настройках
   - с командной строки

   [2025-11-16 Вс 20:30]

   Добавил опцию для задания имени файла в виде спецификатора формата
   внутри шаблона сообщения. Если спецификатор формата есть в шаблоне
   сообщения, то он заменяется на имя файла, иначе сообщение выводится
   таким, каким является шаблон, без преобразований шаблона.

   Новые спецификаторы формата теперь можно добавлять как в сообщения
   одной закачки, так и в сообщение всех закачек, так как эта
   инфраструктура теперь заложена в код на будущее.

