#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)
#+CONSTANTS: last_issue_id=21

* Задачи
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив задач
  :END:

** TASK Добавить возможность отключения уведомлений
   :PROPERTIES:
   :issue_id: 1
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

   - в настройках
   - с командной строки

** TASK Сделать видимую связь временного файла со ссылкой в списке ссылок
   :PROPERTIES:
   :issue_id: 2
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:18]

   Можно вести учёт скачиваемых и скачанных файлов в отдельном файле,
   в котором записывать ссылки и временные или постоянные имена для
   них.

** DONE Задать имя файла рядом со ссылкой в списке ссылок
   CLOSED: [2025-07-02 Ср 00:37]
   :PROPERTIES:
   :issue_id: 3
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:18]

   Возможно для этого больше подойдёт отдельный файл с именами по
   порядку. Имена можно брать и помечать как взятые уже и присвоенные
   каким-то файлам. Надо обдумать этот вопрос, чтобы не перегружать
   сильно файл со ссылками ограничивающим синтаксисом.

   [2025-07-02 Ср 00:38]

   Добавил разделитель возле ссылки, который задаётся в файле
   конфигурации. Если разделитель есть, то берётся имя файла после
   разделителя. Если разделителя нет, то устанавливается имя по
   порядку.

** TASK Сделать информативный режим отладки при загрузке ссылки
   :PROPERTIES:
   :issue_id: 4
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

** TASK Провести ссылку из исходника страницы через преобразования
   :PROPERTIES:
   :issue_id: 5
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

   Найденную в тексте ссылку нужно почистить перед открытием, так как
   найдена бывает какая-то js-внутренность с символами бэкслеша и
   другими.

   На каждом этапе полученная ссылка должна преобразовываться в
   соответствии с её индивидуальной настройкой.

** TASK Атрибуты xml переделать в текстовые узлы
   :PROPERTIES:
   :issue_id: 6
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:18]

   При наличии графического или консольного интерфейса для любой
   работы с файлом настроек то, как хранятся настройки, в атрибутах
   или в полноценных узлах в виде текста, становится неважно.

** TASK Сделать настройку для изображения браузера
   :PROPERTIES:
   :issue_id: 7
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

   - агента
   - реферера

** TASK Сделать отладочный помощник для проверки файла настройки
   :PROPERTIES:
   :issue_id: 8
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

   Он должен показывать, находится ли ссылка, без её загрузки. Это
   вроде отладки, но который официально помогает сформировать файл
   настроек и показывает заранее результаты по нему.

** TASK Сделать возможность взятия ссылок из потока ввода
   :PROPERTIES:
   :issue_id: 9
   :issue_type: task
   :END:

   [2025-06-07 Сб 21:04]

   Сейчас ссылки могут браться только из файла, но бывает, что нужно
   закачать одну ссылку, при этом используя основной файл настроек.

** TASK Сделать возможность перекрытия настроек из командной строки
   :PROPERTIES:
   :issue_id: 10
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:18]

   Иногда какую-то настройку надо временно подменить, но не
   затрагивать эту настройку на постоянной основе. Поэтому нужно
   сделать возможность быстрой подмены любой настройки или нескольких
   настроек через командную строку.

** TASK Вывести сообщение при отсутствии файла настроек
   :PROPERTIES:
   :issue_id: 18
   :issue_type: task
   :END:

   [2025-06-06 Пт 23:46]

   Когда запускаешь программу в директории, в которой нет файла
   настроек, порождается непонятное исключение. Надо сделать так,
   чтобы выводилось сообщение об отсутствии файла и подсказка.

** TASK Сделать интерфейс для создания и заполнения файла настроек
   :PROPERTIES:
   :issue_id: 19
   :issue_type: task
   :END:

   [2025-06-06 Пт 23:49]

   Так как файл настроек имеет формат XML, его неудобно заполнять
   вручную от начала до конца. Также в XML требуются специальные
   экранирования многих символов. Также в файле настроек используются
   регулярные выражения, которые тоже требуют экранирования символов в
   контексте регулярного выражения. Для всего этого нужно сделать
   простой текстовый интерфейс, который даёт возможность создать файл
   настроек от начала до конца и заполнить его полностью.

** TASK Добавить полноценный набор аргументов командной строки
   :PROPERTIES:
   :issue_id: 21
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:18]

   Полноценный набор - это набор аргументов, построенный на модуле
   argparse.

* Баги
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив багов
  :END:

** BUG Имя файла после его загрузки формировать во время сохранения
   :PROPERTIES:
   :issue_id: 11
   :issue_type: bug
   :END:

   [2025-06-14 Сб 10:18]

   Если имя выбрано в самом начале закачки, то в середине закачки
   список файлов может быть изменён (удалены файлы). Когда закачка
   завершена, нужно учитывать новый состав файлов, а не сохранять под
   начальным.

   Надо сделать начальное имя. Если начальное имя свободно во время
   сохранения, то использовать его. Иначе нужно применить стратегию на
   случай занятого начального имени.

** BUG Исключить два закачивания в один файл
   :PROPERTIES:
   :issue_id: 12
   :issue_type: bug
   :END:

   [2025-06-14 Сб 10:18]

   При коллизии временных имён должна срабатывать стратегия и быть
   видна пользователю. Если временные имена используют слишком
   короткую рандомную последовательность, то множественные коллизии
   становятся более вероятными. В случае коллизии можно запрещать
   скачку второго файла или пропускать её, пока первый файл не
   докачается.

* Окружение
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив окружения
  :END:

** TASK Перевести строчные комментарии на английский язык
   :PROPERTIES:
   :issue_id: 22
   :issue_type: task
   :END:

   [2025-06-14 Сб 10:24]
